import assert from 'node:assert/strict'
import { resourceHistory, resourceSegments, resourceValue } from '../src/games/stardew/resource-metrics-presentation.ts'
import { resourceAmount, resourceBytes, resourceComparison, resourcePercent, resourceRing, resourceShare, resourceShareText } from '../src/games/resource-presentation.ts'

const sample = { timestamp: '2026-09-15T00:00:00Z', containerRunning: true, cpuPercent: 0, memoryPercent: 42, diskPercent: 11.3 }
assert.equal(resourceValue(sample, 'cpuPercent'), 0)
assert.equal(resourceValue({ ...sample, cpuPercent: 240 }, 'cpuPercent'), 240)
assert.equal(resourceValue({ ...sample, containerRunning: false }, 'cpuPercent'), null)
assert.equal(resourceValue({ ...sample, containerRunning: false }, 'diskPercent'), 11.3)
for (const bad of [NaN, Infinity, -1, null]) assert.equal(resourceValue({ ...sample, memoryPercent: bad }, 'memoryPercent'), null)
assert.equal(resourceValue({ ...sample, diskPercent: 110 }, 'diskPercent'), 100)
const at = (seconds: number, cpuPercent: number | null = 10) => ({ ...sample, timestamp: new Date(Date.parse(sample.timestamp) + seconds * 1000).toISOString(), cpuPercent })
const history = resourceHistory([at(16), at(0), at(8), at(8, 20), { ...sample, timestamp: 'invalid' }])
assert.deepEqual(history.map(s => s.cpuPercent), [10, 20, 10])
assert.equal(resourceSegments(history, 'cpuPercent').length, 1)
assert.deepEqual(resourceSegments([at(0), at(8, null), at(16), at(48)], 'cpuPercent').map(s => s.length), [1, 1, 1])
assert.equal(resourceBytes(0), '0 B')
assert.equal(resourceBytes(3.6 * 1024 ** 3), '3.6 GB')
assert.equal(resourcePercent(0), '0%')
assert.equal(resourceRing(132), 100)
assert.equal(resourceShare(25, 100), 25)
assert.equal(resourceShare(0, 100), 0)
assert.equal(resourceShare(100, 100), 100)
assert.equal(resourceShareText(resourceShare(1.9, 932)), '0.2%')
assert.equal(resourceShareText(0.001), '<0.1%')
assert.equal(resourceShareText(0), '0%')
assert.equal(resourceShareText(0.1), '0.1%')
assert.equal(resourceShare(101, 100), null)
for (const total of [undefined, null, 0, -1, NaN, Infinity]) assert.equal(resourceShare(1, total), null)
for (const bad of [undefined, null, NaN, Infinity, -1]) {
  assert.equal(resourceBytes(bad), '—')
  assert.equal(resourcePercent(bad), '—')
  assert.equal(resourceRing(bad), 0)
  assert.equal(resourceShare(bad, 100), null)
  assert.equal(resourceShareText(bad), '—')
}
const machine = { ...sample, scope: 'machine' as const, cpuCount: 8, cpuPercent: 22.4, memoryPercent: 61.7, memoryUsedBytes: 9.872 * 1024 ** 3, memoryTotalBytes: 16 * 1024 ** 3, diskPercent: 11.3, diskUsedBytes: 105 * 1024 ** 3, diskTotalBytes: 932 * 1024 ** 3 }
const game = { ...sample, scope: 'game' as const, cpuPercent: 1.2, memoryPercent: 7, memoryUsedBytes: 1.12 * 1024 ** 3, storageUsedBytes: 1.9 * 1024 ** 3 }
const cpu = resourceComparison('cpu', game, machine)
assert.equal(`${cpu.primary}/${cpu.secondary}${cpu.unit}`, '1.2/22.4%')
assert.equal(cpu.machinePercent, 22.4)
assert.equal(resourceComparison('cpu', game, { ...machine, cpuPercent: 0 }).machinePercent, 0)
assert.equal(resourceComparison('cpu', game).machinePercent, null)
assert.equal(resourceComparison('cpu', game, { ...machine, cpuPercent: NaN }).machinePercent, null)
assert.equal(resourceComparison('cpu', { ...game, cpuPercent: 40 }, machine).machinePercent, 22.4)
assert.match(cpu.detail, /游戏合计：0.1 核\n整机已用：1.79 核\n整机总量：8 核/)
const memory = resourceComparison('memory', game, machine)
assert.equal(`${memory.primary}/${memory.secondary}${memory.unit}`, '7/61.7%')
assert.match(memory.detail, /游戏合计：1.1 GB\n整机已用：9.9 GB\n整机总量：16 GB/)
const storage = resourceComparison('storage', { ...game, scope: 'world' }, machine)
assert.equal(`${storage.primary}/${storage.secondary}${storage.unit}`, '0.2/11.3%')
assert.match(storage.detail, /当前世界：1.9 GB\n整机已用：105 GB\n数据盘容量：932 GB/)
assert.equal(resourceComparison('cpu', { ...game, cpuPercent: 0 }, machine).primary, '0')
assert.equal(resourceComparison('cpu', { ...game, cpuPercent: 0.001 }, machine).primary, '<0.1')
assert.equal(resourceComparison('cpu', undefined, machine).secondary, '22.4')
assert.equal(resourceComparison('cpu', game).primary, '1.2')
assert.equal(resourceComparison('cpu', game).secondary, '—')
assert.equal(resourceComparison('cpu').unit, '')
assert.match(resourceComparison('cpu', undefined, undefined, 'world').detail, /当前世界：—/)
assert.equal(resourceComparison('cpu', { ...game, cpuPercent: NaN }, machine).percent, null)
assert.equal(resourceComparison('storage', game).percent, null)
assert.equal(resourceAmount('cpu', { ...machine, cpuCores: 123 }), '1.79 核')
assert.equal(resourceAmount('cpu', { ...game, cpuPercent: null, cpuCores: 1 }, machine), '—')
assert.equal(resourceAmount('memory', { ...game, memoryPercent: null }), '—')
console.log('Resource metrics: scopes, own/host comparisons, tooltip amounts, zero, missing, stopped, multicore, invalid, ordering and sampling gaps passed')
