import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import {
  maxPlayersValidationError,
  runtimeSettingsEffectText,
  runtimeSettingsOnlineWarning,
  shouldShowPlayerLimitAction,
} from '../src/games/stardew/server-runtime-settings-state.ts'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8').replace(/\r\n?/g, '\n')

assert.equal(maxPlayersValidationError(1), null)
assert.equal(maxPlayersValidationError(100), null)
assert.notEqual(maxPlayersValidationError(0), null)
assert.notEqual(maxPlayersValidationError(101), null)
assert.notEqual(maxPlayersValidationError(1.5), null)
assert.equal(runtimeSettingsOnlineWarning(3, 4), '目标上限低于当前在线 4 人；仍可仅保存，重启后才会生效。')
assert.equal(runtimeSettingsOnlineWarning(4, 4), null)
assert.equal(runtimeSettingsOnlineWarning(1, null), null)
assert.equal(shouldShowPlayerLimitAction(true, true), true)
assert.equal(shouldShowPlayerLimitAction(false, true), false)
assert.equal(shouldShowPlayerLimitAction(true, false), false)
assert.equal(runtimeSettingsEffectText({ isRunning: true, currentMaxPlayers: 10, configuredMaxPlayers: 16 }), '当前生效上限 10 人；重启后配置 16 人，存在待重启变更。')
assert.equal(runtimeSettingsEffectText({ isRunning: true, currentMaxPlayers: 10, configuredMaxPlayers: 10 }), '当前生效上限与重启后配置均为 10 人。')
assert.equal(runtimeSettingsEffectText({ isRunning: false, currentMaxPlayers: 10, configuredMaxPlayers: 16 }), '服务器已停止；配置上限 16 人将在下次启动时生效。')

const desktop = read('../src/games/stardew/pages/ServerControlPage.tsx')
const desktopCss = read('../src/games/stardew/pages/ServerControlPage.css')
const mobile = read('../src/games/stardew/mobile/MobileControlPage.tsx')
const overview = read('../src/games/stardew/pages/OverviewPage.tsx')
const overviewCss = read('../src/games/stardew/pages/OverviewPage.css')
const summary = read('../src/games/stardew/ServerSummaryCard.tsx')
const dialog = read('../src/games/stardew/ServerRuntimeSettingsDialog.tsx')
const dialogCss = read('../src/games/stardew/ServerRuntimeSettingsDialog.css')
const shellCss = read('../src/games/stardew/StardewPanel.css')
const hook = read('../src/games/stardew/useServerRuntimeSettings.ts')

for (const [name, source] of [['desktop', desktop], ['mobile', mobile]] as const) {
  assert.match(source, /useServerRuntimeSettings\(\{/, `${name} must use the shared runtime settings state flow`)
  assert.match(source, /<ServerRuntimeSettingsDialog/, `${name} must use the shared runtime settings form`)
  assert.match(source, /currentMaxPlayers=\{dashboardData\.players\?\.maxPlayers \?\? null\}/)
  assert.match(source, /人数上限 \/ 小屋策略 \/ 广播频率/)
  assert.match(source, /restartServer:/, `${name} must delegate restart to the shared lifecycle flow`)
  assert.match(source, /onSaveAndRestart=\{\(\) => \{ void handleSaveRuntimeSettings\(true\) \}\}/)
}

assert.match(desktop, /canEditPlayerLimit=\{isAdmin\}/)
assert.match(desktop, /onEditPlayerLimit=\{\(\) => \{ void openRuntimeSettings\(\) \}\}/)
assert.match(summary, /canEditPlayerLimit: boolean/)
assert.match(summary, /onEditPlayerLimit\?: \(\) => void/)
assert.match(summary, /shouldShowPlayerLimitAction\(canEditPlayerLimit, Boolean\(onEditPlayerLimit\)\)/)
assert.match(summary, /修改上限/)
assert.match(summary, /sd-server-summary-item--editable/)
assert.match(summary, /icon_top_summary_save\.png/)
assert.match(summary, /icon_topbar_user_avatar_image2_v2\.png/)
assert.match(summary, /sd-server-summary-farmer-icon/)
assert.match(shellCss, /\.sd-server-summary-label img\.sd-server-summary-farmer-icon\s*\{[^}]*object-fit:\s*cover[^}]*object-position:\s*50% 10%/s)
assert.match(shellCss, /\.sd-server-summary-limit-btn\s*\{[^}]*min-height:\s*44px/s)
assert.match(shellCss, /\.sd-server-summary-label img\s*\{[^}]*width:\s*22px[^}]*height:\s*22px[^}]*filter:\s*none/s)
assert.match(desktopCss, /\.sd-server-summary-label img\s*\{[^}]*width:\s*22px[^}]*height:\s*22px[^}]*filter:\s*none/s)
assert.match(shellCss, /\.sd-server-summary-item--editable\s*\{[^}]*padding-right:\s*92px/s)
assert.match(shellCss, /\.sd-server-summary-limit-btn\s*\{[^}]*position:\s*absolute[^}]*top:\s*50%[^}]*margin:\s*0/s)
assert.doesNotMatch(shellCss, /\.sd-server-summary-limit-btn\s*\{[^}]*margin:\s*-\d/s)

assert.match(overview, /useServerRuntimeSettings\(\{/)
assert.match(overview, /<ServerRuntimeSettingsDialog/)
assert.match(overview, /isAdmin \? \([\s\S]*?sd-ov-player-limit-btn[\s\S]*?修改上限/)
assert.match(overview, /restartServer:\s*handleRestart/)
assert.match(overviewCss, /\.sd-ov-player-limit-btn\s*\{[^}]*max-width:\s*100%[^}]*min-height:\s*44px/s)
assert.match(overviewCss, /\.sd-ov-card \.sd-player-hd\s*\{[^}]*flex-wrap:\s*wrap/s)

assert.match(dialog, /type="number"/)
assert.match(dialog, /className="sd-runtime-number-stepper"/)
assert.match(dialog, /aria-label="减少最大同时在线人数"/)
assert.match(dialog, /aria-label="增加最大同时在线人数"/)
assert.match(dialog, /min=\{1\}/)
assert.match(dialog, /max=\{100\}/)
assert.match(dialog, /step=\{1\}/)
assert.match(dialog, /范围 1~100，包含主机位。降低上限不会删除已有角色或小屋。/)
assert.match(dialog, /<fieldset className="sd-runtime-advanced">/)
assert.match(dialog, /runtimeSettingsOnlineWarning\(draft\.maxPlayers, onlineCount\)/)
assert.match(dialog, /保存并重启/)
assert.match(dialog, /role="alertdialog"/)
assert.match(dialog, /当前有 \$\{onlineCount\} 名玩家在线/)
assert.match(dialog, /onSaveAndRestart\(\)/)
assert.match(dialog, /\|\| !isRunning/)
assert.match(dialog, /saving \|\| Boolean\(validationError\)/)
assert.doesNotMatch(dialog, /disabled=\{[^}]*onlineWarning/)
assert.match(dialogCss, /\.sd-runtime-dialog-btn\s*\{[^}]*min-height:\s*44px/s)
assert.match(dialogCss, /\.sd-runtime-number-input\s*\{[^}]*appearance:\s*textfield/s)
assert.match(dialogCss, /\.sd-runtime-number-input::\-webkit-inner-spin-button,[\s\S]*?appearance:\s*none/s)
assert.match(dialogCss, /\.sd-runtime-stepper-btn\s*\{[^}]*min-width:\s*44px[^}]*min-height:\s*44px/s)
assert.match(dialogCss, /\.sd-runtime-actions\s*\{[^}]*grid-template-columns:\s*auto auto minmax\(12px, 1fr\) auto/s)
assert.match(dialogCss, /\.sd-runtime-save-restart-btn\s*\{[^}]*grid-column:\s*4/s)
assert.match(dialogCss, /@media \(max-width: 420px\)/)

assert.match(hook, /updateInstanceServerRuntimeSettings\(runtimeSettingsDraft\)/)
assert.match(hook, /await refreshPlayers\(\)/)
assert.match(hook, /await restartServer\(\)/)
assert.match(hook, /设置已保存，但服务器重启失败/)
assert.match(hook, /isRunning[\s\S]*?下次启动时生效/)

console.log('runtime player limit regression checks passed')
