import assert from 'node:assert/strict'
import { jobErrorSummary, jobEventLabel, jobStatusLabel, localizedJobName, shortEventTime } from '../src/core/job-presentation.ts'
import { formatStardewLocation } from '../src/games/stardew/location-format.ts'
import { routeToPath } from '../src/games/stardew/stardew-routes.ts'

assert.equal(localizedJobName({ type: 'stardew_lifecycle', operation: 'start' }), '启动服务器')
assert.equal(localizedJobName({ type: 'stardew_lifecycle', operation: 'stop' }), '停止服务器')
assert.equal(localizedJobName({ type: 'stardew_lifecycle' }), '服务器操作')
assert.equal(localizedJobName({ type: 'stardew_lifecycle', operation: 'future_action' }), '服务器操作')
assert.equal(localizedJobName({ type: 'stardew_lifecycle', operation: 'restart', displayName: 'stardew_lifecycle' }), '重启服务器')
assert.equal(localizedJobName({ type: 'mod_remote_install', displayName: 'Farm Type Manager (FTM) · mod_remote_install' }), 'Farm Type Manager (FTM) · 安装远程模组')
assert.equal(localizedJobName({ type: 'future_task' }), '后台任务')
assert.equal(localizedJobName({ type: 'stardew_install', displayName: '重新安装游戏' }), '重新安装游戏')
assert.equal(jobEventLabel({ type: 'stardew_lifecycle', status: 'succeeded' }), '服务器操作已完成', 'legacy lifecycle events must not invent a start operation')
assert.equal(jobEventLabel({ type: 'stardew_lifecycle', operation: 'stop', status: 'succeeded' }), '服务器已停止')
assert.equal(jobEventLabel({ type: 'stardew_install', status: 'failed' }), '游戏安装失败')
assert.equal(jobEventLabel({ type: 'stardew_install', status: 'queued' }), '安装游戏 · 排队中')
assert.deepEqual(['queued', 'running', 'succeeded', 'failed', 'canceled', 'future'].map(jobStatusLabel), ['排队中', '进行中', '已完成', '失败', '已取消', '状态未知'])
assert.match(jobErrorSummary('SteamCMD install finished without success marker'), /没有确认游戏下载完成/)
assert.match(jobErrorSummary('context deadline exceeded'), /超时/)
assert.match(jobErrorSummary('bind: address already in use'), /端口已被占用/)
assert.match(jobErrorSummary('no space left on device'), /存储空间或磁盘配额不足/)
assert.equal(jobErrorSummary('存档未能加载，请检查模组。'), '存档未能加载，请检查模组。')
assert.match(jobErrorSummary('unrecognized technical failure'), /原始诊断信息/, 'unknown diagnostics remain available without an invented explanation')
assert.match(jobErrorSummary(null), /任务未能完成/)
assert.equal(shortEventTime('invalid'), '时间未知')
const time = new Date(2026, 8, 17, 7, 3).toISOString()
assert.equal(shortEventTime(time), '9/17 07:03')
assert.equal(routeToPath('jobs', { jobId: 'job one&two' }, 'river-farm'), '/instances/river-farm/jobs?jobId=job+one%26two')
assert.equal(routeToPath('jobs', undefined, 'stardew'), '/instances/stardew/jobs')
assert.equal(formatStardewLocation({ locationDisplayName: '1111 Farm', tileX: 64, tileY: 15 }), '1111 农场 (64, 15)')
assert.equal(formatStardewLocation({ locationName: 'FarmHouse' }), '农舍')
assert.equal(formatStardewLocation({ locationDisplayName: 'Custom Farmhouse' }), 'Custom Farmhouse', 'custom location names must not be partially translated')
console.log('Job presentation: lifecycle evidence, names, states, errors, dates and farm location labels passed')
